name: notmiwae
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - numpy
      - tensorflow==2.13.0 # last version compatible with macOS 13
      # - tensorflow-probability==0.21.0
      - tf-keras==2.15.0
      - matplotlib
      - pandas
      - scikit-learn
      - jupyter
      - ucimlrepo